theme: jekyll-theme-cayman
title: "Meepingsnesroms code stuffs"
description: "It always runs on everything!"
mysite.url: "https://meepingsnesroms.github.io"
github:
   owner_name: "meepingsnesroms"
   owner_url: "https://github.com/meepingsnesroms"
